id: I3DC74754
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T22:25:41.765715'
last_modified: '2022-06-18T22:25:41.765729'
parser: null
source_metadata:
  title: Catuḥśataka of Āryadeva (Old Gong dkar block print), colophon excerpt
  author: སློབ་དཔོན་འཕགས་པ་ལྷ།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2017-10-16);
    revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:-
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Mathias Fermer (mf)
  text_witnesses: https://sakyaresearch.org/sources/1393
  bases:
    5d31:
      title: Catuḥśataka of Āryadeva (Old Gong dkar block print), colophon excerpt
      order: 1
      base_file: 5d31.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
